Факториал и проверка ввода
js-tasks-ru/jsbasic-20200903_imhonlix pull request #2
Opened 2020-09-15 11:03 UTC by Honlixi

2020-09-15 11:10 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Вычислить факториал
+ факториал 1 равен 1
+ факториал 3 равен 6 
+ факториал 0 равен 1
+ факториал 5 равен 120 
```
```diff
Допишите функцию валидации имени пользователя
+ если имя корректное, то true
+ если содержит пробелы, то false
+ если меньше 4 символов то false
```

Добавляю преподавателя (@koalex) для код-ревью, посмотрим что он скажет :)

2020-09-16 01:13 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
Сделать первый символ заглавным
+ должна работать для строки из одной буквы
+ должна делать первый символ заглавным
- должна работать для пустой строки
```
```diff
Вычислить факториал
+ факториал 0 равен 1
+ факториал 1 равен 1
+ факториал 5 равен 120 
+ факториал 3 равен 6 
```
```diff
Допишите функцию валидации имени пользователя
+ если меньше 4 символов то false
+ если содержит пробелы, то false
+ если имя корректное, то true
```

2020-09-16 01:33 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
Вычислить факториал
+ факториал 5 равен 120 
+ факториал 3 равен 6 
+ факториал 1 равен 1
+ факториал 0 равен 1
```
```diff
Допишите функцию валидации имени пользователя
+ если имя корректное, то true
+ если содержит пробелы, то false
+ если меньше 4 символов то false
```
```diff
Сделать первый символ заглавным
+ должна делать первый символ заглавным
+ должна работать для строки из одной буквы
- должна работать для пустой строки
```

2020-09-16 01:38 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2020-09-17 07:52 UTC, koalex requested changes
Исправь замечание

2020-09-17 07:52 UTC, koalex commented on 1-module/1-task/README.md
> +factorial(5); // 120 функция for n != 1 sum *= n - i
убери строки с 29 по 32. В коде не должно быть вызовов ф-ции `factorial()`

2020-09-17 09:43 UTC, Honlixi commented on 1-module/1-task/README.md
> +factorial(5); // 120 функция for n != 1 sum *= n - i
Так это же README.md.. У меня в коде нет разрывов.
function factorial(n) {
    let sum = 1;
    for (let i = 0; i != n; ++i) {
        sum = sum * (n - i);
    }
    return sum;
} // вот мой код

2020-09-17 10:39 UTC, Honlixi commented on 1-module/1-task/README.md
> +factorial(5); // 120 функция for n != 1 sum *= n - i
Это про 3 задание 1 модуль
Там ошибка, но я не понимаю где. Я вроде исправил

2020-09-17 12:34 UTC, koalex approved these changes

2020-09-17 12:34 UTC, merged